spring:
    datasource:
        url: jdbc:mysql://192.168.100.180:3306/haolei_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        username: haolei_developer
        password: 123456
#        driver-class-name: com.mysql.jdbc.Driver
        driverClassName: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery:  SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            
    redis:  
      host: localhost  
      port: 6379  
      password:  myredis
      pool:  
       max-active: 8  
       max-idle: 8  
       min-idle: 0  
       max-wait: 10000  
       
       
       
       
       
       